/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const readExternalProduct_Logic = require('./code/readExternalProduct-logic');

class cap_simple_reqSrv extends LCAPApplicationService {
    async init() {

        this.on('READ', 'ExtProducts', async (request, next) => {
            return readExternalProduct_Logic(request, next);
        });

        return super.init();
    }
}


module.exports = {
    cap_simple_reqSrv
};